# mongodb
spring.data.mongodb.uri: mongodb://alocquet:alocquet@192.168.99.100:30040/poc

# Jackson Date format
spring.jackson.serialization.write_dates_as_timestamps: false

logging.level.org.springframeworks: DEBUG
